name: CI Pipeline

# Kịch bản này sẽ tự động kích hoạt khi có code mới đẩy lên nhánh chính
on:
  push:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # GitHub sẽ cấp tạm một máy ảo Ubuntu miễn phí để chạy

    steps:
      - name: Lấy code mới nhất từ repository
        uses: actions/checkout@v3

      - name: Tiến hành kiểm tra đóng gói Docker
        run: docker build -t devops-demo-app .
