name: CI Pipeline

<<<<<<< HEAD
# Kịch bản này sẽ tự động kích hoạt khi có code mới đẩy lên nhánh chính
=======
>>>>>>> b9f1cb8
on:
  push:
    branches: ["main", "master"]

jobs:
  build-and-test:
<<<<<<< HEAD
    runs-on: ubuntu-latest # GitHub sẽ cấp tạm một máy ảo Ubuntu miễn phí để chạy

    steps:
      - name: Lấy code mới nhất từ repository
        uses: actions/checkout@v3

      - name: Tiến hành kiểm tra đóng gói Docker
=======
    runs-on: ubuntu-latest y

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Build Docker image
>>>>>>> b9f1cb8
        run: docker build -t devops-demo-app .
